---
title: "p8105_hw2_jz4027"
author: "Charlotte Zhang"
date: "2025-09-26"
output: html_document
---
```{r}
# Load needed library
library(tidyverse)
```

# Problem 1
```{r}
pols_month_df = 
  # import and clean pols-month data
  read_csv("./fivethirtyeight_datasets/pols-month.csv", na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  # split mon into year, month, day
  separate(mon, into = c("year", "month", "day"), sep = "-") |>
  mutate(
    # convert to integers
    year = as.integer(year),
    month = as.integer(month),
    day = as.integer(day),
    # replace month number with month name
    month = month.name[month],
    # create a president variable taking values gop and dem
    president = if_else(prez_gop == 1, "gop", "dem")
  ) |>
  # remove three variables
  select(-day, -prez_gop, -prez_dem)

pols_month_df
```

```{r}
snp_df = 
  # import and clean snp data
  read_csv("./fivethirtyeight_datasets/snp.csv", na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  # split date into month, day, year
  separate(date, into = c("month", "day", "year"), sep = "/") |>
  mutate(
    # convert to integers
    year = as.integer(year),
    # Change from 2-integer years to 4-integer
    year = if_else(year > 25, 1900 + year, 2000 + year),
    month = as.integer(month),
    day = as.integer(day),
    # replace month number with month name
    month = month.name[month]) |>
  select (year, month, close) |>
  # arrange according to year and month
  arrange(year, month)

snp_df
```

```{r}
unemployment_df = 
  # import and clean unemployment data
  read_csv("./fivethirtyeight_datasets/unemployment.csv", na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  pivot_longer(
    jan:dec,
    names_to = 'month',
    values_to = 'unemployment',
  ) |>
  mutate(
    month = str_to_title(month),            # the first letter of each month is capitalized
    month = match(month, month.abb),        # convert abbreviation → month number
    month = month.name[month]               # convert month number to full month name for format consistency 
  )

unemployment_df
```







