p8105_hw2_jz4027
================
Charlotte Zhang
2025-09-26

``` r
# Load needed library
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(readxl)
library(janitor)
```

    ## 
    ## Attaching package: 'janitor'
    ## 
    ## The following objects are masked from 'package:stats':
    ## 
    ##     chisq.test, fisher.test

# Problem 1

### Clean the pols_month data set

``` r
pols_month_df = 
  # import and clean pols-month data
  read_csv("./fivethirtyeight_datasets/pols-month.csv", na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  # split mon into year, month, day
  separate(mon, into = c("year", "month", "day"), sep = "-") |>
  mutate(
    # convert to integers
    year = as.integer(year),
    month = as.integer(month),
    day = as.integer(day),
    # replace month number with month name
    month = month.name[month],
    # create a president variable taking values gop and dem
    president = if_else(prez_gop == 1, "gop", "dem")
  ) |>
  # remove three variables
  select(-day, -prez_gop, -prez_dem)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
pols_month_df
```

    ## # A tibble: 822 × 9
    ##     year month     gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <int> <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ##  1  1947 January        23      51     253      23      45     198 dem      
    ##  2  1947 February       23      51     253      23      45     198 dem      
    ##  3  1947 March          23      51     253      23      45     198 dem      
    ##  4  1947 April          23      51     253      23      45     198 dem      
    ##  5  1947 May            23      51     253      23      45     198 dem      
    ##  6  1947 June           23      51     253      23      45     198 dem      
    ##  7  1947 July           23      51     253      23      45     198 dem      
    ##  8  1947 August         23      51     253      23      45     198 dem      
    ##  9  1947 September      23      51     253      23      45     198 dem      
    ## 10  1947 October        23      51     253      23      45     198 dem      
    ## # ℹ 812 more rows

### Clean the snp data set

``` r
snp_df = 
  # import and clean snp data
  read_csv("./fivethirtyeight_datasets/snp.csv", na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  # split date into month, day, year
  separate(date, into = c("month", "day", "year"), sep = "/") |>
  mutate(
    # convert to integers
    year = as.integer(year),
    # Change from 2-integer years to 4-integer
    year = if_else(year > 25, 1900 + year, 2000 + year),
    month = as.integer(month),
    day = as.integer(day)) |>
  select(year, month, close) |>
  # arrange according to year and month
  arrange(year, month) |>
  # replace month number with month name
  mutate(
    month = month.name[month])
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
snp_df
```

    ## # A tibble: 787 × 3
    ##     year month     close
    ##    <dbl> <chr>     <dbl>
    ##  1  1950 January    17.0
    ##  2  1950 February   17.2
    ##  3  1950 March      17.3
    ##  4  1950 April      18.0
    ##  5  1950 May        18.8
    ##  6  1950 June       17.7
    ##  7  1950 July       17.8
    ##  8  1950 August     18.4
    ##  9  1950 September  19.5
    ## 10  1950 October    19.5
    ## # ℹ 777 more rows

### Clean the unemployment data set

``` r
unemployment_df = 
  # import and clean unemployment data
  read_csv("./fivethirtyeight_datasets/unemployment.csv", na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  pivot_longer(
    jan:dec,
    names_to = 'month',
    values_to = 'unemployment',
  ) |>
  mutate(
    month = str_to_title(month),            # the first letter of each month is capitalized
    month = match(month, month.abb),        # convert abbreviation → month number
    month = month.name[month]               # convert month number to full month name for format consistency 
  )
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
unemployment_df
```

    ## # A tibble: 816 × 3
    ##     year month     unemployment
    ##    <dbl> <chr>            <dbl>
    ##  1  1948 January            3.4
    ##  2  1948 February           3.8
    ##  3  1948 March              4  
    ##  4  1948 April              3.9
    ##  5  1948 May                3.5
    ##  6  1948 June               3.6
    ##  7  1948 July               3.6
    ##  8  1948 August             3.9
    ##  9  1948 September          3.8
    ## 10  1948 October            3.7
    ## # ℹ 806 more rows

### Merge

``` r
snp_pols_merged_df = 
  left_join(pols_month_df, snp_df, by = c("year", "month"))

unemployment_merged_df =
  left_join(snp_pols_merged_df, unemployment_df, by = c("year", "month"))
unemployment_merged_df
```

    ## # A tibble: 822 × 11
    ##     year month   gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president close
    ##    <dbl> <chr>     <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>     <dbl>
    ##  1  1947 January      23      51     253      23      45     198 dem          NA
    ##  2  1947 Februa…      23      51     253      23      45     198 dem          NA
    ##  3  1947 March        23      51     253      23      45     198 dem          NA
    ##  4  1947 April        23      51     253      23      45     198 dem          NA
    ##  5  1947 May          23      51     253      23      45     198 dem          NA
    ##  6  1947 June         23      51     253      23      45     198 dem          NA
    ##  7  1947 July         23      51     253      23      45     198 dem          NA
    ##  8  1947 August       23      51     253      23      45     198 dem          NA
    ##  9  1947 Septem…      23      51     253      23      45     198 dem          NA
    ## 10  1947 October      23      51     253      23      45     198 dem          NA
    ## # ℹ 812 more rows
    ## # ℹ 1 more variable: unemployment <dbl>

### Explain and describe

pols_month csv file contains the number of politicians (sen, rep, gov,
prez) affiliated with the GOP and the democratic party each month,
throughout many years. It also shows which party hold the presidency by
using 0 and 1. Then, the snp data set contains different dates and their
corresponding SP closing value. The date column of the snp data set was
also reformatted/cleaned for consistency across data sets. The
unemployment data set includes monthly unemployment rate from 1948 to
2015, switched from the original wide format (month as column names) to
long format for better format consistency. The resulting combined data
set has a dimension of 822, 11 (rows and columns, respectively). It has
a year range between 1947, 2015. Key variables include: year, month,
gov_gop, sen_gop, rep_gop, gov_dem, sen_dem, rep_dem, president, close,
unemployment.

# Problem 2

### Clean and organize data for Mr. Trash Wheel

``` r
# Clean and organize data for Mr. Trash Wheel
Mr_df = read_excel("202509 Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel", range = "A2:N709" ) |>
  janitor::clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(sports_balls = as.integer(round(sports_balls)),
         year = as.integer(year),
         trash_wheel = "mr. trash wheel") 
```

### Clean and organize data for Professor Trash Wheel

``` r
# Clean and organize data for Professor Trash Wheel
Professor_df = read_excel("202509 Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel") |>
  janitor::clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(year = as.integer(year),
         trash_wheel = "professor trash wheel")
```

### Clean and organize data for Gwynns_df

``` r
# Clean and organize data for Gwynns_df
Gwynns_df = read_excel("202509 Trash Wheel Collection Data.xlsx", sheet = "Gwynns Falls Trash Wheel") |>
  janitor::clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(year = as.integer(year),
         trash_wheel = "gwynns falls trash wheel")
```

### Combine

``` r
# Combine
P2_combined <- bind_rows(Mr_df, Professor_df, Gwynns_df)
```

### Description

``` r
prof_total_weight <- P2_combined |>
  filter(trash_wheel == "professor trash wheel") |>
  summarise(total_weight = sum(weight_tons, na.rm = TRUE)) |>
  pull(total_weight)

gwynns_june2022_cigarette <- P2_combined |>
  filter(month == "June", year == 2022, trash_wheel == "gwynns falls trash wheel") |>
  summarise(total_cig_butts = sum(cigarette_butts, na.rm = TRUE)) |>
  pull(total_cig_butts)
```

The resulting combined trash wheel dataset contains 1188 observations.
Each row corresponds to a dumpster removal event, with key variables
including the date, weight of trash, volume of trash, the name of the
trash wheel, and the counts of specific types of collected litters. Here
is a list of all variables in the combined dataset: dumpster, month,
year, date, weight_tons, volume_cubic_yards, plastic_bottles,
polystyrene, cigarette_butts, glass_bottles, plastic_bags, wrappers,
sports_balls, homes_powered, trash_wheel. The total weight of trash
collected by Professor Trash Wheel is 282.26. The total number of
cigarette butts collected by Gwynnda in June of 2022 is 1.812^{4}.

# Problem 3

``` r
# Import and read the data sets
zip_codes_df = 
  read_csv("./zillow_data/Zip Codes.csv", na = c("NA", ".", "")) |>
  janitor::clean_names()
```

    ## Rows: 322 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (4): County, County Code, File Date, Neighborhood
    ## dbl (3): State FIPS, County FIPS, ZipCode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
zori_df = 
  read_csv("./zillow_data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv", na = c("NA", ".", "")) |>
  janitor::clean_names()
```

    ## Rows: 149 Columns: 125
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr   (6): RegionType, StateName, State, City, Metro, CountyName
    ## dbl (119): RegionID, SizeRank, RegionName, 2015-01-31, 2015-02-28, 2015-03-3...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

### Clean zori_df

``` r
# Clean zori_df
zori_df_cleaned <- zori_df |>
  rename(zip_code = region_name) |>
  # state name is the same thing as state
  select(-state_name) |>
  pivot_longer(
    cols = starts_with("x20"),  
    names_to = "date",
    values_to = "zori") |>
  mutate(date = str_remove(date, "^x"),
         zori = as.numeric(zori),
         county_name = str_remove(county_name, "\\s+County$")) |>
  separate(date, into = c("zori_year", "zori_month", "zori_day"), sep = "_") |>
  relocate(zip_code, county_name) |>
  arrange(zip_code, county_name)
```

### Clean zip_codes_df

``` r
# Clean zip_codes_df
zip_codes_df_cleaned <- zip_codes_df |>
  relocate(zip_code, county) |>  
  arrange(zip_code, county)
```

### Merged and resulting tidy dataset

``` r
# Combine zip_codes_df_cleaned with zori_df_cleaned
p3_merged = left_join(zip_codes_df_cleaned, zori_df_cleaned, by = "zip_code", relationship = "many-to-many") |>
  mutate(
    zori_year = as.integer(zori_year),
    zori_month = as.integer(zori_month),
    zori_day = as.integer(zori_day)
  ) |>
  arrange(zip_code)
```

Description: In the resulting tidy dataset, there are 17687
observations. The number of unique zip codes is 320. The number of
unique neighborhood is 43.

### Unique zips in zip_codes csv

``` r
# zip code in zip_codes_df_cleaned only, not zori_df_cleaned
anti_join(zip_codes_df_cleaned, zori_df_cleaned, by = "zip_code") |>
  arrange(neighborhood)
```

    ## # A tibble: 171 × 7
    ##    zip_code county   state_fips county_code county_fips file_date neighborhood  
    ##       <dbl> <chr>         <dbl> <chr>             <dbl> <chr>     <chr>         
    ##  1    11239 Kings            36 047               36047 7/25/07   Canarsie and …
    ##  2    10020 New York         36 061               36061 7/25/07   Chelsea and C…
    ##  3    10474 Bronx            36 005               36005 7/25/07   Hunts Point a…
    ##  4    11412 Queens           36 081               36081 7/25/07   Jamaica       
    ##  5    11423 Queens           36 081               36081 7/25/07   Jamaica       
    ##  6    11433 Queens           36 081               36081 7/25/07   Jamaica       
    ##  7    11436 Queens           36 081               36081 7/25/07   Jamaica       
    ##  8    11359 Queens           36 081               36081 7/25/07   North Queens  
    ##  9    10475 Bronx            36 005               36005 7/25/07   Northeast Bro…
    ## 10    11362 Queens           36 081               36081 7/25/07   Northeast Que…
    ## # ℹ 161 more rows

There are 171 zip codes that are in the zip_codes dataset but not in the
Zillow Rental Price dataset. The most likely reason is that Zillow
excludes areas where there are too few rental listings to get a reliable
estimate, such as zip code 10475 (North Bronx) and 11362 (Northeast
Queens). These two places are highly local/residential with less
tourists/commercial businesses which means lower demand of residential
house rentals. And places like Queens Jamaica neighborhood are not in
the zillow dataset possibly due to them being an industrial/airport zone
with few or no residential homes for rent.

### Covid price drop

``` r
# covid price drop top 10
jan2020 <- p3_merged |> filter(zori_month == 1, zori_year == 2020)
jan2021 <- p3_merged |> filter(zori_month == 1, zori_year == 2021)
covid_price_comp <- jan2020 |>
  select(zip_code, county, neighborhood, zori_2020 = zori) |>
  inner_join(jan2021 |> select(zip_code, zori_2021 = zori), by = "zip_code", relationship = "many-to-many") |>
  mutate(
    diff = zori_2021 - zori_2020
  ) |>
  arrange(diff) |>
  slice(1:10)
knitr::kable(covid_price_comp)
```

| zip_code | county   | neighborhood                  | zori_2020 | zori_2021 |      diff |
|---------:|:---------|:------------------------------|----------:|----------:|----------:|
|    10007 | New York | Lower Manhattan               |  6334.211 |  5421.614 | -912.5966 |
|    10069 | New York | NA                            |  4623.042 |  3874.918 | -748.1245 |
|    10009 | New York | Lower East Side               |  3406.442 |  2692.187 | -714.2550 |
|    10016 | New York | Gramercy Park and Murray Hill |  3731.135 |  3019.431 | -711.7045 |
|    10001 | New York | Chelsea and Clinton           |  4108.098 |  3397.648 | -710.4499 |
|    10002 | New York | Lower East Side               |  3645.416 |  2935.113 | -710.3028 |
|    10004 | New York | Lower Manhattan               |  3149.658 |  2443.697 | -705.9608 |
|    10038 | New York | Lower Manhattan               |  3573.201 |  2875.616 | -697.5853 |
|    10012 | New York | Greenwich Village and Soho    |  3628.566 |  2942.344 | -686.2218 |
|    10010 | New York | Gramercy Park and Murray Hill |  3697.284 |  3012.353 | -684.9304 |

The ten ZIP codes with the largest rental price drops between January
2020 and January 2021 were all located in New York County (Manhattan).
Zip code 10007 in the lower Manhattan neighborhood had the most dramatic
Zillow Observed Rent Index drop, from 6334.21 to 5421.614, a difference
of about -912.59. These ten zip codes and neighborhoods contain many
residential units, but are also considered as touristy, busy, and linked
to office employment. During the pandemic, the reduction in tourists and
shift to remote work may have reduced the rental demand, which help
explain the large price drops.
